prSections:
  - title: My Pull Requests
    filters: >-
      is:open
      author:@me
  - title: Needs My Review
    filters: >-
      is:open
      review-requested:@me
      owner:Doist
  - title: Involved
    filters: >-
      is:open
      involves:@me
      -author:@me
  - title: Me last week
    filters: >-
      author:@me
      owner:Doist
      created:>{{ nowModify "-1w2d" }}
  - title: Omar
    filters: >-
      author:odsamuels
      owner:Doist
      created:>{{ nowModify "-1w2d" }}
  - title: Dawid
    filters: >-
      author:dmgawel
      owner:Doist
      created:>{{ nowModify "-1w2d" }}
  - title: David
    filters: >-
      author:miottid
      owner:Doist
      created:>{{ nowModify "-1w2d" }}
  - title: Jef
    filters: >-
      author:JefCurtis
      owner:Doist
      created:>{{ nowModify "-1w2d" }}
issuesSections:
  - title: Brand Dev
    filters: >-
      project:Doist/87
      is:open
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
notificationsSections:
  - title: All
    filters: ""
  - title: Created
    filters: reason:author
  - title: Participating
    filters: reason:participating
  - title: Mentioned
    filters: reason:mention
  - title: Review Requested
    filters: reason:review-requested
  - title: Assigned
    filters: reason:assign
  - title: Subscribed
    filters: reason:subscribed
  - title: Team Mentioned
    filters: reason:team-mention
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 0.45
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  notificationsLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  prs:
    - key: T
      command: gh enhance -R {{.RepoName}} {{.PrNumber}}
    - key: C
      command: cd {{.RepoPath }}; claude "/pr-review {{.PrNumber}}"
repoPaths: { Doist/*: /Users/anton/dev/doist/* }
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: "diffnav --side-by-side"
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
includeReadNotifications: true
